
import { EventEmitter } from 'events';
import { Injectable, Logger } from '@nestjs/common';
import { OpenAIRealtimeSocketHandler } from '@ai-services/ai-helper';

/**
 * Configuration options for creating an OpenAI RTC (Real-Time Communication) session.
 * These options control the behavior and settings of the real-time audio processing session.
 */
export interface OpenAiRtcSessionOptions {
  /**
   * The OpenAI model to use for the real-time session.
   * @default 'gpt-4o-realtime-preview'
   */
  model?: string;

  /**
   * The voice identifier for text-to-speech output.
   * @default 'alloy'
   */
  voice?: string;

  /**
   * Sample rate for incoming audio data in Hz.
   * @default 24000
   */
  inputSampleRate?: number;

  /**
   * Sample rate for outgoing audio data in Hz.
   * @default 24000
   */
  outputSampleRate?: number;

  /**
   * Custom instructions to guide the AI's behavior during the session.
   * If not provided, default translation instructions are used.
   */
  instructions?: string;

  /**
   * Maximum number of reconnection attempts before giving up.
   * @default 3
   */
  maxRetries?: number;

  /**
   * Base delay in milliseconds between reconnection attempts.
   * The actual delay increases exponentially with each retry.
   * @default 500
   */
  baseRetryDelayMs?: number;
}

/**
 * Payload structure for partial transcript events.
 * Emitted as the AI transcribes speech in real-time.
 */
export type PartialTranscriptPayload = {
  /**
   * The incremental text added in this update.
   */
  delta: string;

  /**
   * The complete accumulated transcript text so far.
   */
  text: string;
};

/**
 * Payload structure for text-to-speech audio chunks.
 * Contains the audio data generated by the AI's speech synthesis.
 */
export type TtsChunkPayload = {
  /**
   * Base64-encoded audio data.
   */
  base64: string;

  /**
   * Audio format identifier (e.g., 'pcm16').
   */
  format: string;

  /**
   * Sample rate of the audio in Hz.
   */
  sampleRate: number;

  /**
   * Optional identifier linking this audio to a specific response.
   */
  responseId?: string;
};

/**
 * Interface defining the contract for an OpenAI RTC session.
 * Provides methods for establishing connection, sending audio, and controlling the session.
 */
export interface OpenAiRtcSession {
  /**
   * EventEmitter for receiving session events such as transcripts, audio chunks, and errors.
   *
   * ## Events Emitted
   * - `tts.chunk` - Text-to-speech audio chunk received (payload: {@link TtsChunkPayload})
   * - `transcript.partial` - Partial transcript update (payload: {@link PartialTranscriptPayload})
   * - `error` - An error occurred during the session
   */
  events: EventEmitter;

  /**
   * Establishes a connection to the OpenAI real-time API.
   * @returns A Promise that resolves when the connection is established.
   */
  connect(): Promise<void>;

  /**
   * Sends an audio chunk to OpenAI for processing.
   * @param chunk - The raw PCM audio data buffer to send.
   */
  sendAudioChunk(chunk: Buffer): void;

  /**
   * Commits the accumulated audio buffer, signaling that the current speech segment is complete.
   */
  commitAudio(): void;

  /**
   * Requests the AI to generate a response based on the accumulated audio input.
   * @param instructions - Optional instructions to override the default session instructions.
   */
  requestResponse(instructions?: string): void;

  /**
   * Closes the session and releases all resources.
   */
  close(): void;
}

/**
 * Default instructions for the AI when no custom instructions are provided.
 * Configures the AI as a simultaneous translator from German to English.
 */
const DEFAULT_INSTRUCTIONS =
  'You are a simultaneous translator. Translate continuously from German to English. Respond only with the translation, no comments.';

/**
 * Service for creating and managing OpenAI Real-Time Communication sessions.
 *
 * This service provides a factory method for creating RTC sessions that enable
 * real-time audio streaming and processing with OpenAI's API. It handles:
 * - WebSocket connection management with automatic reconnection
 * - Audio streaming for speech-to-text and translation
 * - Text-to-speech audio output streaming
 * - Session lifecycle management
 *
 * ## Usage Example
 *
 * ```typescript
 * @Injectable()
 * class TranslationService {
 *   constructor(private rtcService: OpenAiRtcService) {}
 *
 *   async startTranslation() {
 *     const session = this.rtcService.createSession({
 *       voice: 'alloy',
 *       instructions: 'Translate from German to English.',
 *     });
 *
 *     session.events.on('tts.chunk', (chunk: TtsChunkPayload) => {
 *       // Handle audio output
 *     });
 *
 *     session.events.on('transcript.partial', (transcript: PartialTranscriptPayload) => {
 *       console.log('Transcript:', transcript.text);
 *     });
 *
 *     await session.connect();
 *     session.sendAudioChunk(audioBuffer);
 *   }
 * }
 * ```
 */
@Injectable()
export class OpenAiRtcService {
  /**
   * Creates a new OpenAI RTC session with the specified options.
   *
   * @param options - Configuration options for the session. All options are optional
   *                  and will use sensible defaults if not provided.
   *
   * @returns A new {@link OpenAiRtcSession} instance ready for connection.
   *
   * @example
   * ```typescript
   * const session = rtcService.createSession({
   *   model: 'gpt-4o-realtime-preview',
   *   voice: 'alloy',
   *   inputSampleRate: 24000,
   *   outputSampleRate: 24000,
   *   maxRetries: 5,
   * });
   * ```
   */
  createSession(options: OpenAiRtcSessionOptions = {}): OpenAiRtcSession {
    return new OpenAiRtcSessionImpl(options);
  }
}

/**
 * Internal implementation of the OpenAI RTC session.
 *
 * This class manages the WebSocket connection to OpenAI's real-time API,
 * handles audio streaming, and provides automatic reconnection with
 * exponential backoff on connection failures.
 *
 * @internal
 */
class OpenAiRtcSessionImpl implements OpenAiRtcSession {
  /**
   * EventEmitter for broadcasting session events to subscribers.
   */
  events = new EventEmitter();

  /**
   * Logger instance for diagnostic output and debugging.
   */
  private readonly logger = new Logger(OpenAiRtcSessionImpl.name);

  /**
   * Session configuration options with defaults applied.
   */
  private readonly options: OpenAiRtcSessionOptions;

  /**
   * The underlying OpenAI socket handler instance.
   */
  private handler: OpenAIRealtimeSocketHandler | null = null;

  /**
   * Flag indicating whether the session has been explicitly closed.
   */
  private closed = false;

  /**
   * Current count of reconnection attempts.
   */
  private retryCount = 0;

  /**
   * Timer reference for scheduled reconnection attempts.
   */
  private retryTimer?: NodeJS.Timeout;

  /**
   * Queue of audio chunks pending transmission until connection is ready.
   */
  private pendingAudio: Buffer[] = [];

  /**
   * Accumulated partial transcript text.
   */
  private partialTranscript = '';

  /**
   * Flag indicating whether the connection is ready for audio transmission.
   */
  private ready = false;

  /**
   * Creates a new session implementation instance.
   *
   * @param options - Configuration options for the session.
   */
  constructor(options: OpenAiRtcSessionOptions) {
    this.options = options;
  }

  /**
   * Establishes a connection to the OpenAI real-time API.
   *
   * This method creates a new WebSocket connection and configures the session.
   * If called while already connected, it will close the existing connection
   * and establish a new one.
   *
   * @returns A Promise that resolves when the connection is established.
   */
  async connect(): Promise<void> {
    if (this.closed) {
      return;
    }

    if (this.retryTimer) {
      clearTimeout(this.retryTimer);
      this.retryTimer = undefined;
    }
    this.ready = false;

    if (this.handler) {
      this.handler.close();
    }

    this.handler = new OpenAIRealtimeSocketHandler({
      model: this.options.model,
      voice: this.options.voice,
      inputSampleRate: this.options.inputSampleRate ?? 24_000,
      outputSampleRate: this.options.outputSampleRate ?? 24_000,
      instructions: this.options.instructions ?? DEFAULT_INSTRUCTIONS,
    });

    this.attachHandlers(this.handler);

    try {
      await this.handler.connectToAudioStream();
      this.retryCount = 0;
      this.ready = true;
      this.flushPendingAudio();
    } catch (error) {
      this.logger.error('Failed to connect to OpenAI RTC session', error as Error);
      this.scheduleReconnect('connect_failed');
    }
  }

  /**
   * Sends an audio chunk to OpenAI for processing.
   *
   * If the connection is not yet ready, the chunk is queued and will be
   * sent automatically once the connection is established.
   *
   * @param chunk - The raw PCM audio data buffer to send.
   */
  sendAudioChunk(chunk: Buffer): void {
    if (this.closed) {
      return;
    }

    if (!this.ready || !this.handler) {
      this.pendingAudio.push(chunk);
      return;
    }

    this.handler.sendAudioChunk(chunk);
  }

  /**
   * Commits the accumulated audio buffer for processing.
   *
   * This signals to OpenAI that all audio chunks sent are ready to be processed.
   * Should be called after sending all audio data for a speech segment.
   */
  commitAudio(): void {
    if (!this.handler || !this.ready) {
      return;
    }

    this.handler.commitAudio();
  }

  /**
   * Requests the AI to generate a response based on the accumulated audio input.
   *
   * @param instructions - Optional instructions to override the default session
   *                       instructions for this specific response.
   */
  requestResponse(instructions?: string): void {
    if (!this.handler || !this.ready) {
      return;
    }

    this.handler.requestResponse(instructions ?? this.options.instructions ?? DEFAULT_INSTRUCTIONS);
  }

  /**
   * Closes the session and releases all resources.
   *
   * After calling this method, the session cannot be reused and a new session
   * must be created for further communication.
   */
  close(): void {
    this.closed = true;
    if (this.retryTimer) {
      clearTimeout(this.retryTimer);
      this.retryTimer = undefined;
    }
    this.handler?.close();
  }

  /**
   * Attaches event handlers to the OpenAI socket handler.
   *
   * Routes events from the handler to the session's event emitter and
   * handles error recovery through automatic reconnection.
   *
   * @param handler - The OpenAI socket handler instance to attach to.
   * @private
   */
  private attachHandlers(handler: OpenAIRealtimeSocketHandler): void {
    handler.events.on('audio.output', (payload) => {
      this.events.emit('tts.chunk', payload as TtsChunkPayload);
    });

    handler.events.on('transcript', (delta) => {
      if (typeof delta === 'string') {
        this.partialTranscript += delta;
        const payload: PartialTranscriptPayload = {
          delta,
          text: this.partialTranscript,
        };
        this.events.emit('transcript.partial', payload);
      }
    });

    handler.events.on('response.complete', () => {
      this.partialTranscript = '';
    });

    handler.events.on('error', (err) => {
      this.logger.warn('OpenAI RTC session error', err as Error);
      this.events.emit('error', err);
      this.scheduleReconnect('error_event');
    });

    handler.events.on('close', (info) => {
      if (!this.closed) {
        this.logger.warn('OpenAI RTC session closed unexpectedly', info as Error);
        this.scheduleReconnect('socket_closed');
      }
    });
  }

  /**
   * Flushes any pending audio chunks that were queued before the connection was ready.
   *
   * @private
   */
  private flushPendingAudio(): void {
    if (!this.handler || !this.ready || this.pendingAudio.length === 0) {
      return;
    }

    const queued = [...this.pendingAudio];
    this.pendingAudio = [];
    queued.forEach((chunk) => this.handler?.sendAudioChunk(chunk));
  }

  /**
   * Schedules a reconnection attempt with exponential backoff.
   *
   * The delay between retries doubles with each attempt, starting from
   * the configured `baseRetryDelayMs`. After reaching `maxRetries`,
   * an error event is emitted and no further reconnection attempts are made.
   *
   * @param reason - A descriptive reason for the reconnection attempt (for logging).
   * @private
   */
  private scheduleReconnect(reason: string): void {
    if (this.closed) {
      return;
    }

    const maxRetries = this.options.maxRetries ?? 3;
    if (this.retryCount >= maxRetries) {
      this.events.emit('error', new Error(`OpenAI RTC session retry limit reached (${reason}).`));
      return;
    }

    const delay = (this.options.baseRetryDelayMs ?? 500) * Math.pow(2, this.retryCount);
    this.retryCount += 1;
    this.logger.warn(`Scheduling OpenAI RTC reconnect in ${delay} ms (${reason})`);
    this.retryTimer = setTimeout(() => {
      void this.connect();
    }, delay);
  }
}
